### ISSUE TITLE
Line 23,24 & 25 causes an error.

### ISSUE THREAD

**Issue by JayRizzo** [behave/behave.example#8]
Hi, 

Thank you for your example this helped me get started on configuring my pylint.

I wanted to let you know the statement `# path. You may set this option multiple times.` is no longer true in my instance of python3

```
pylint ~/Documents/mymodule.py 
Traceback (most recent call last):
  File "/anaconda3/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/anaconda3/lib/python3.6/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/anaconda3/lib/python3.6/site-packages/pylint/lint.py", line 1301, in __init__
    linter.read_config_file()
  File "/anaconda3/lib/python3.6/site-packages/pylint/config.py", line 654, in read_config_file
    parser.read_file(fp)
  File "/anaconda3/lib/python3.6/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/anaconda3/lib/python3.6/configparser.py", line 1092, in _read
    fpname, lineno)
**configparser.DuplicateOptionError: While reading from '/Users/jkirchoff/.pylintrc' [line 24]: option 'ignore' in section 'MASTER' already exists**

```

**Comment by jenisys** [comment]
Thx, integrated.
